apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ml-service-allow-namespace
spec:
  podSelector:
    matchLabels:
      app: ml-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}   # allow all pods in namespace
